name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - name: disable auto CRLF
      run: git config --global core.autoCRLF false
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build
    - run: npm test
