name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: disable auto CRLF
        run: git config --global core.autoCRLF false
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test

  integrated:
    name: integrated test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: test-${{ github.run_id }}
          release_name: Test for ${{ github.run_id }}
          draft: true
          prerelease: true
          body: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - uses: ./
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/*.js
